### ISSUE TITLE
[Bug] 多音字问题、韵母ü问题

### ISSUE THREAD

**Issue by Phoupraw** [Cyrillya/RecipeBrowserPinyin#1]
- “南瓜”只能由“nagua”匹配，不能由“nangua”匹配。
- “钥匙”只能由“yuechi”匹配，不能由“yaoshi”匹配。
- “调皮”只能由“diaopi”匹配，不能由“tiaopi”匹配。
- “绿”只能由“lu”匹配，不能由“lv”匹配。

**Comment by Cyrillya** [comment]
~~无能力解决，这是C#版NPinyin库的问题，给我提issue也没用~~

由于换成了PinyinNet，以上问题全部完美解决

**Comment by Cyrillya** [comment]
换成了PinyinNet，问题解决
